# Generated by Django 4.2.11 on 2024-06-16 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="title_az",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="brand",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="title_az",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="title_az",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="title_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productsubcategory",
            name="title_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="productversion",
            name="description_az",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productversion",
            name="description_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productversion",
            name="description_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productversion",
            name="title_az",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productversion",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productversion",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
