# Generated by Django 4.2.11 on 2024-06-28 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="productcolor",
            name="title_az",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productcolor",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="productsize",
            name="title_az",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productsize",
            name="title_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productsize",
            name="title_ru",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="producttag",
            name="title_az",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="producttag",
            name="title_en",
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="producttag",
            name="title_ru",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
