# Generated by Django 5.0.4 on 2024-05-17 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_discount_remove_productversion_discount_percent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='productversion',
            name='product',
        ),
        migrations.AddField(
            model_name='productversion',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_versions', to='product.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productversion',
            name='subcategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='product_versions', to='product.productsubcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productversion',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='product_tags', to='product.producttag'),
        ),
        migrations.AddField(
            model_name='productversion',
            name='size',
            field=models.ManyToManyField(blank=True, to='product.productsize'),
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
