# Generated by Django 4.2.11 on 2024-07-06 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0003_remove_productsize_title_az_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="brand",
            name="image",
            field=models.ImageField(null=True, upload_to="brand_image"),
        ),
    ]
