# Generated by Django 4.2.11 on 2024-07-06 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0004_brand_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="TopBrand",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("image", models.ImageField(null=True, upload_to="brand_image")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
