# Generated by Django 4.2.11 on 2024-07-08 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0005_topbrand"),
    ]

    operations = [
        migrations.AddField(
            model_name="productversion",
            name="is_new",
            field=models.BooleanField(default=True),
        ),
    ]
