# Generated by Django 4.2.11 on 2024-07-10 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0006_productversion_is_new"),
    ]

    operations = [
        migrations.CreateModel(
            name="SpecialDiscount",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percent", "Percentage"), ("amount", "Amount")],
                        max_length=10,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "product_version",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="special_discounts",
                        to="product.productversion",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
