# Generated by Django 4.2.11 on 2024-07-11 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0007_specialdiscount"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productversion",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.AlterModelOptions(
            name="specialdiscount",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Daily Special Discount",
                "verbose_name_plural": "Daily Special Discounts",
            },
        ),
        migrations.CreateModel(
            name="ProductDetail",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("processor", models.CharField(max_length=100)),
                ("screen_diagonal", models.CharField(max_length=100)),
                ("video_card", models.CharField(max_length=100)),
                ("ram", models.CharField(max_length=100)),
                ("memory", models.CharField(max_length=100)),
                ("screen_indicators", models.CharField(max_length=100)),
                ("operating_system", models.CharField(max_length=100)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="product.productversion",
                    ),
                ),
            ],
            options={
                "verbose_name": "Product Detail",
                "verbose_name_plural": "Product Details",
                "ordering": ["-created_at"],
            },
        ),
    ]
