# Generated by Django 4.2.11 on 2024-07-11 01:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0008_alter_productversion_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productdetail",
            name="product",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="product.productversion",
            ),
        ),
    ]
