# Generated by Django 4.2.11 on 2024-07-13 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0010_alter_brand_options_alter_discount_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=50)),
                ("title_az", models.CharField(max_length=50, null=True)),
                ("title_en", models.CharField(max_length=50, null=True)),
                ("title_ru", models.CharField(max_length=50, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("brands", models.ManyToManyField(to="product.brand")),
                (
                    "parent_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="child_cats",
                        to="product.category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["id"],
            },
        ),
        migrations.RemoveField(
            model_name="productsubcategory",
            name="category",
        ),
        migrations.AlterModelOptions(
            name="productversion",
            options={
                "ordering": ["created_at"],
                "verbose_name": "Product",
                "verbose_name_plural": "Products",
            },
        ),
        migrations.RemoveField(
            model_name="productversion",
            name="subcategory",
        ),
        migrations.DeleteModel(
            name="ProductCategory",
        ),
        migrations.DeleteModel(
            name="ProductSubcategory",
        ),
        migrations.AddField(
            model_name="productversion",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_versions",
                to="product.category",
            ),
        ),
    ]
