# Generated by Django 4.2.11 on 2024-07-12 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_alter_brand_options_alter_discount_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productversion',
            options={'ordering': ['created_at'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
    ]
