# Generated by Django 4.2.11 on 2024-07-15 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0011_category_remove_productsubcategory_category_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="icon",
            field=models.ImageField(blank=True, null=True, upload_to="category_icons/"),
        ),
    ]
