# Generated by Django 4.2.11 on 2024-07-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0012_category_icon"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Slider",
        ),
    ]
