# Generated by Django 4.2.11 on 2024-07-22 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0013_delete_slider"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDetailType",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Product Detail Type",
                "verbose_name_plural": "Product Detail Types",
                "ordering": ["id"],
            },
        ),
    ]
