# Generated by Django 4.2.11 on 2024-07-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("product", "0014_productdetailtype"),
    ]

    operations = [
        migrations.AddField(
            model_name="productdetailtype",
            name="name_az",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productdetailtype",
            name="name_en",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name="productdetailtype",
            name="name_ru",
            field=models.CharField(max_length=50, null=True),
        ),
    ]
