# Generated by Django 4.2.11 on 2024-07-29 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_productversion_options'),
        ('product', '0017_productdetail_value_az_productdetail_value_en_and_more'),
    ]

    operations = [
    ]
