# Generated by Django 4.2.11 on 2024-07-11 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_category_description_az_category_description_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="image",
            field=models.ImageField(null=True, upload_to="blog_image"),
        ),
    ]
