# Generated by Django 4.2.11 on 2024-07-16 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_blog_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="subtitle",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
