# Generated by Django 4.2.11 on 2024-07-16 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_blog_subtitle"),
    ]

    operations = [
        migrations.AddField(
            model_name="blog",
            name="subtitle_az",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="subtitle_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="blog",
            name="subtitle_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
