# Generated by Django 4.2.11 on 2024-06-18 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FacebookProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Facebook Profile",
            },
        ),
        migrations.CreateModel(
            name="InstagramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Instagram Profile",
            },
        ),
        migrations.CreateModel(
            name="TelegramProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Telegram Profile",
            },
        ),
        migrations.CreateModel(
            name="TiktokProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Tiktok Profile",
            },
        ),
        migrations.CreateModel(
            name="WhatsappProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.URLField()),
            ],
            options={
                "verbose_name": "Whatsapp Profile",
            },
        ),
    ]
