# Generated by Django 4.2.11 on 2024-07-16 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("title_az", models.CharField(max_length=100, null=True)),
                ("title_en", models.CharField(max_length=100, null=True)),
                ("title_ru", models.CharField(max_length=100, null=True)),
                ("description", models.TextField()),
                ("description_az", models.TextField(null=True)),
                ("description_en", models.TextField(null=True)),
                ("description_ru", models.TextField(null=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Home Page Banner",
                "verbose_name_plural": "Home Page Banner",
                "ordering": ["-created_at"],
            },
        ),
    ]
